(source gnu)
(source melpa)
(source marmalade)

(depends-on "init-loader")
(depends-on "bind-key")
(depends-on "helm")

(depends-on "ac-ispell")
(depends-on "ace-jump-mode")
(depends-on "ag")
(depends-on "anzu")
(depends-on "auto-complete")
(depends-on "bm")
(depends-on "elscreen")
(depends-on "exec-path-from-shell")
(depends-on "expand-region")
(depends-on "flycheck")
(depends-on "flycheck-cask")
(depends-on "flycheck-pos-tip")
(depends-on "git-gutter")
(depends-on "helm-c-yasnippet")
(depends-on "helm-etags-plus" :git "https://github.com/jixiuf/helm-etags-plus.git")
(depends-on "helm-ghq")
(depends-on "helm-ls-git")
(depends-on "helm-swoop")
(depends-on "idle-highlight-mode")
(depends-on "js2-mode" :git "https://github.com/mooz/js2-mode.git")
(depends-on "lispxmp")
(depends-on "magit")
(depends-on "multi-term")
(depends-on "multiple-cursors")
(depends-on "paredit")
(depends-on "projectile")
(depends-on "pbcopy")
(depends-on "popup")
(depends-on "popwin")
(depends-on "rbenv")
(depends-on "recentf-ext")
(depends-on "robe")
(depends-on "smartparens")
(depends-on "smartrep")
(depends-on "undo-tree")
(depends-on "wgrep")
(depends-on "yasnippet")
(depends-on "zop-to-char")

(depends-on "coffee-mode")
(depends-on "feature-mode")
(depends-on "go-mode")
(depends-on "js2-mode")
(depends-on "json-mode")
(depends-on "markdown-mode")
(depends-on "motion-mode")
(depends-on "nginx-mode")
(depends-on "php-mode")
(depends-on "puppet-mode")
(depends-on "rspec-mode")
(depends-on "ruby-mode")
(depends-on "scss-mode")
(depends-on "terraform-mode")
(depends-on "web-mode")
(depends-on "yaml-mode")

(source org)
(depends-on "org-plus-contrib")
