(add-to-list 'load-path "~/.emacs.d/el-get/el-get")

(unless (require 'el-get nil 'noerror)
  (package-install 'el-get)
  (require 'el-get))

(add-to-list 'el-get-recipe-path "~/.emacs.d/el-get-user/recipes")

(el-get-bundle bind-key)
(el-get-bundle helm)

(el-get-bundle melpa:ac-alchemist)
(el-get-bundle melpa:ac-ispell)
(el-get-bundle melpa:ace-jump-mode)
(el-get-bundle melpa:ag)
(el-get-bundle melpa:alchemist)
(el-get-bundle melpa:anzu)
(el-get-bundle melpa:auto-complete)
(el-get-bundle melpa:auto-highlight-symbol)
(el-get-bundle melpa:bm)
(el-get-bundle melpa:company)
(el-get-bundle melpa:dash-at-point)
(el-get-bundle melpa:ddskk)
(el-get-bundle melpa:elscreen)
(el-get-bundle melpa:exec-path-from-shell)
(el-get-bundle melpa:expand-region)
(el-get-bundle melpa:flycheck)
(el-get-bundle melpa:flycheck-cask)
(el-get-bundle melpa:flycheck-credo)
(el-get-bundle melpa:flycheck-elixir)
(el-get-bundle melpa:flycheck-pos-tip)
(el-get-bundle melpa:free-keys)
(el-get-bundle melpa:git-gutter)
(el-get-bundle melpa:helm-ag)
(el-get-bundle melpa:helm-c-yasnippet)
(el-get-bundle melpa:helm-etags-plus)
(el-get-bundle melpa:helm-ghq)
(el-get-bundle melpa:helm-ls-git)
(el-get-bundle melpa:helm-swoop)
(el-get-bundle melpa:init-open-recentf)
(el-get-bundle melpa:js2-mode)
(el-get-bundle melpa:json-reformat)
(el-get-bundle melpa:lispxmp)
(el-get-bundle melpa:magit)
(el-get-bundle melpa:multi-term)
(el-get-bundle melpa:multiple-cursors)
(el-get-bundle melpa:org-seek)
(el-get-bundle melpa:ox-gfm)
(el-get-bundle melpa:paredit)
(el-get-bundle melpa:pbcopy)
(el-get-bundle melpa:popup)
(el-get-bundle melpa:popwin)
(el-get-bundle melpa:projectile)
(el-get-bundle melpa:rbenv)
(el-get-bundle melpa:recentf-ext)
(el-get-bundle melpa:ripgrep)
(el-get-bundle melpa:robe)
(el-get-bundle melpa:smartparens)
(el-get-bundle melpa:smartrep)
(el-get-bundle melpa:string-inflection)
(el-get-bundle melpa:undo-tree)
(el-get-bundle melpa:w3m)
(el-get-bundle melpa:wgrep)
(el-get-bundle melpa:wgrep-ag)
(el-get-bundle melpa:yaoddmuse)
(el-get-bundle melpa:yasnippet)
(el-get-bundle melpa:zop-to-char)

(el-get-bundle rcodetools
  :url "https://raw.githubusercontent.com/hirocaster/.emacs.d/master/vendor/rcodetools/rcodetools.el")

(el-get-bundle direnv
  :url "https://raw.githubusercontent.com/hirocaster/.emacs.d/master/vendor/direnv/direnv.el")

(el-get-bundle melpa:coffee-mode)
(el-get-bundle melpa:dockerfile-mode)
(el-get-bundle melpa:elixir-mode)
(el-get-bundle melpa:enh-ruby-mode)
(el-get-bundle melpa:feature-mode)
(el-get-bundle melpa:go-mode)
(el-get-bundle melpa:js2-mode)
(el-get-bundle melpa:json-mode)
(el-get-bundle melpa:markdown-mode)
(el-get-bundle melpa:motion-mode)
(el-get-bundle melpa:nginx-mode)
(el-get-bundle melpa:php-mode)
(el-get-bundle melpa:puppet-mode)
(el-get-bundle melpa:rspec-mode)
(el-get-bundle ruby-mode)
(el-get-bundle melpa:scss-mode)
(el-get-bundle melpa:terraform-mode)
(el-get-bundle melpa:tide)
(el-get-bundle melpa:typescript-mode)
(el-get-bundle melpa:web-mode)
(el-get-bundle melpa:yaml-mode)
