(defun term-send-bol  () (interactive) (term-send-raw-string "\C-a"))
(defun term-send-eol  () (interactive) (term-send-raw-string "\C-e"))

(add-hook 'term-mode-hook '(lambda ()
                             (setq show-trailing-whitespace nil)
                             (add-to-list 'term-unbind-key-list '"C-t")
                             (add-to-list 'term-unbind-key-list '"C-a")
                             (add-to-list 'term-unbind-key-list '"C-p")
                             (add-to-list 'term-unbind-key-list '"C-n")
                             (add-to-list 'term-unbind-key-list '"C-f")
                             (add-to-list 'term-unbind-key-list '"C-b")
                             (add-to-list 'term-unbind-key-list '"C-w")
                             (add-to-list 'term-unbind-key-list '"C-e")
                             (define-key term-raw-map (kbd "C-a") 'term-send-bol)
                             (define-key term-raw-map (kbd "C-e") 'term-send-eol)
                             (define-key term-raw-map (kbd "C-y") 'term-paste)
                             (define-key term-raw-map (kbd "C-h") 'term-send-backspace)
                             (define-key term-raw-map (kbd "M-d") 'term-send-forward-kill-word)
                             (define-key term-raw-map (kbd "C-w") 'term-send-backward-kill-word)
                             (define-key term-raw-map (kbd "M-.") 'term-send-raw-meta)
                             (define-key term-raw-map (kbd "C-z") 'term-send-raw)))
