(defun term-send-bol  () (interactive) (term-send-raw-string "\C-a"))

(defun toggle-term-view () (interactive)
       (cond ((eq major-mode 'term-mode)
              (fundamental-mode)
              (view-mode-enable)
              (local-set-key (kbd "C-g") 'toggle-term-view)
              (setq multi-term-cursor-point (point)))
             ((eq major-mode 'fundamental-mode)
              (view-mode-disable)
              (goto-char multi-term-cursor-point)
              (multi-term-internal))))

(add-hook 'term-mode-hook '(lambda ()
                             (setq show-trailing-whitespace nil)
                             (add-to-list 'term-unbind-key-list '"C-t")
                             (add-to-list 'term-unbind-key-list '"C-a")
                             (add-to-list 'term-unbind-key-list '"C-p")
                             (add-to-list 'term-unbind-key-list '"C-n")
                             (add-to-list 'term-unbind-key-list '"C-f")
                             (add-to-list 'term-unbind-key-list '"C-b")
                             (add-to-list 'term-unbind-key-list '"C-w")
                             (define-key term-raw-map (kbd "C-a") 'term-send-bol)
                             (define-key term-raw-map (kbd "C-y") 'term-paste)
                             (define-key term-raw-map (kbd "C-h") 'term-send-backspace)
                             (define-key term-raw-map (kbd "M-d") 'term-send-forward-kill-word)
                             (define-key term-raw-map (kbd "C-w") 'term-send-backward-kill-word)
                             (define-key term-raw-map (kbd "M-.") 'term-send-raw-meta)
                             (define-key term-raw-map (kbd "C-v") 'toggle-term-view)
                             (define-key term-raw-map (kbd "C-z") 'term-send-raw)))
