(when (eq system-type 'darwin)
  (global-set-key "\C-c\C-x" 'clip-cut)
  (global-set-key "\C-c\C-c" 'clip-copy)
  (global-set-key "\C-c\C-p" 'clip-paste)

  (defun clip-cut (beg end)
    ""
    (interactive "r")
    (let ((cmd "pbcopy")
          (coding-system-for-write 'utf-8))
      (progn  (message "... cut to clipboard")
              (call-process-region beg end cmd nil nil nil "")
              (kill-region beg end)
              (message "")
              )))

  (defun clip-copy (beg end)
    ""
    (interactive "r")
    (let ((cmd "pbcopy")
          (coding-system-for-write 'utf-8))
      (progn  (message "... copy to clipboard")
              (call-process-region beg end cmd nil nil nil "")
              (message "")
              )))

  (defun clip-paste ()
    ""
    (interactive)
    (message "... paste from clipboard")
    (let ((s (point))(e))
      (let ((cmd "pbpaste")
            (coding-system-for-read 'utf-8))
        (call-process cmd nil t nil ""))
      (setq e (point))
      (if (equal e s)
          (ding)
        )
      (message "")))
  )
