(setq howm-menu-lang 'ja)
(autoload 'howm-menu "howm" "Hitori Otegaru Wiki Modoki" t)
(setq howm-directory "~/Dropbox/howm/org")
(setq howm-file-name-format "%Y/%m/%Y%m%d-%H%M%S.org")
(add-hook 'org-mode-hook 'howm-mode)
(setq howm-view-title-header "*")
(setq howm-process-coding-system 'utf-8)
(setq howm-keyword-file "~/Dropbox/howm/.howm-keys")
(setq howm-menu-file "~/Dropbox/howm/menu.txt")
